### ISSUE TITLE
LaTeX formatters

### ISSUE THREAD

**Issue by ArtemyB** [fslaborg/zzarchive-FsLab#119]
As I understood, there are no LaTeX formatters (printers) in FsLab (at least for Deedle Frame and Series and XPlot charts). Would be nice to see them there. 😃
The questions are:
1. How much work is needed to add them?
2. What code parts/services are responsible for such kind features? Is it [F# Interactive Service](https://github.com/ionide/FsInteractiveService)?

**P.S.:** Big thanks for all already existing FsLab features. They're really great! 👍

**Comment by tpetricek** [comment]
I did some significant reworking of how the FsLab journal works, and this sadly broke the (original) support for LaTeX. I decided to start with just HTML, but supporting LaTeX would be great!

The HTML formatting is done by providing `fsi.AddHtmlPrinter` that is called by the various formatters implemented in [FsLab.Formatters](https://github.com/fslaborg/FsLab.Formatters/tree/master/src). Those specify how to turn various objects to HTML and can be also implemented by users.

To support LaTeX formatting, we would need to expose `fsi.AddLatexPrinter` and implement formatters for standard objects using this. It should not be that much work:

 * To add `AddLatexPrinter`, we can pretty much follow [the case of HTML formatter](https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L133). These extensions are then called [here](https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L177) to extract HTML for an evaluated object. The same method could be used to extract LaTeX code and embed it into the output using `InlineBlock` (I suppose the context `ctx` would need a flag specifying whether we are producing HTML or LaTeX output).

 * The HTML formatters (for example [for Math.NET](https://github.com/fslaborg/FsLab.Formatters/blob/master/src/Html/MathNet.fs#L100)) then just call `fsi.AddHtmlPrinter`, so we would need to write ones for LaTeX.

 * The last bit is the code that generates `FsLab.fsx`, which now loads all HTML formatters [see here](https://github.com/fslaborg/FsLab/blob/master/build.fsx#L139) and would need to be extended to also load all LaTeX formatters. This is wrapped in `#if HAS_FSI_ADDHTMLPRINTER` (so that it only runs when called from FsLab, and not from normal FSI that does not support HTML printers).

**Comment by ArtemyB** [comment]
@tpetricek thanks for your detailed explanation. Unfortunately, couldn't figure out this [`addHtmlPrinter`][1] part. Maybe that's because of unknowing the internals of FSI, etc., but I find it a bit mysterious. :thinking:

[1]: https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L133

**Comment by tpetricek** [comment]
That piece of code in a string is (secretly) executed before the F# Interactive service is used to run any code. It defines the `fsi.AddHtmlPrinter` extension (and a module to store the registered printers).

After evaluating any code snippet, we then [here](https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L166) call `FsInteractiveService.tryFormatHtml` (from the module defined in the string) and use the returned formatter to [try format values](https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L174).

(It is a bit messy - I'll be happy to help with this, but I'll be on holidays for the next two weeks. Can you ping me later? If you can create the LaTeX formatters for usual values, I should be able to help with integrating everything when I'm back!)

**Comment by ArtemyB** [comment]
@tpetricek and what about [`__ReflectHelper.ForwardingInteractiveSettings`][1]? For me this type is the most mysterious part in this "string-injection", because I even couldn't find its use somewhere else in code.

P.S.: It seemed to me, that implementing LaTeX formatters should be very similar to HTML ones. So I feel that I could do this. But firstly it's needed to understand, how the code for HTML formatters work.
[1]: https://github.com/fslaborg/FsLab/blob/7c7c2ec9f778cf78810ac518ca4d9b826f24af86/src/FsLab.Runner/Runner.fs#L140

**Comment by dsyme** [comment]
@ArtemyB ForwardInteractiveSettings comes from FAKE Yaaf scripting support.  When your scripts are processed using FsLab literate programming support the scripts are actually processed using FAKE.exe (FAKE version 4.x), which is a little mysterious but gives more hooks to intercept settings etc.

https://github.com/fsharp/FAKE/blob/575330d8eab58177152bc79963b3b21599aef76e/paket-files/matthid/Yaaf.FSharp.Scripting/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L1388

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
