### ISSUE TITLE
latex index.tex not creating links

### ISSUE THREAD

**Issue by TonyAbell** [fslaborg/zzarchive-FsLab#68]
When there are multible fsx files being generated an index.tex is made.  

And there is a coresponding tex document for each fsx file.  Howerver the index.tex does not properly link them when the final pdf is generated.  

note: using MikTex

**Comment by tpetricek** [comment]
This is not very well tested/planned feature.

I wonder what the most reasonable behavior for latex output with multiple experiments would be. I actually think we should probably merge the documents (rather than generating separate files). Separate files make sense for HTML but not for PDF.

Any PRs improving this are welcome!

**Comment by dsyme** [comment]
FsLab is now changing to be an incubation space for F# data science projects, per discussion in https://github.com/fslaborg/zzarchive-FsLab/issues/137#issuecomment-741093688

Closing this out as it relates to the old FsLab package collection.
